services:
  taco:
    container_name: taco
    image: api.taco
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:4131
      - Kestrel__Certificates__Default__Path=/https/aspnetcore.pfx
      - Kestrel__Certificates__Default__Password=sC7xSn5yG3Zl0Wc
    volumes:
      - ./data-protection:/root/.aspnet/DataProtection-Keys
      - ./aspnetcore.pfx:/https/aspnetcore.pfx
      - ./keys/daring-avenue-471019-k3-32d0a3196e0c.json:/keys/daring-avenue-471019-k3-32d0a3196e0c.json:ro
      #.\generate-and-install-cert.ps1 -ServiceName "taco" -ContainerName "taco"
    networks:
      - api-net

networks:
  api-net:
    external: true